<?php
if (!isset($data)) {
    $data = array();
}

?>
<html>
    <head>
        <title>Rent house in all country in benin</title>
    </head>
    <script  src="<?php $this->url->getBaseUri(); ?>public/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/css/style.css" type="text/css">
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/css/animate.css" type="text/css">
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/fontawesome/css/font-awesome.css" >
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/fontawesome/fonts/font-awesome.less" >
    <link rel="stylesheet" href="../<?php $this->url->getBaseUri(); ?>public/fontawesome/fonts/icons.less" >

    <body>

        <div class="build" align="center">
            <div class="contain_all">
                <div class="band_fixe">
                    <div class="band_profil">
                        <div class="profil">
                            <?php foreach ($data as $value): ?>
                                <img src="../public/image/<?php
                                if (!empty($value->img_profile)):echo $value->img_profile;
                                else: echo "default-user-man.png";
                                endif;

                                ?>" class="img-responsive" alt="profil-tof" width="100%" height="100%">
                                 <?php endforeach; ?>
                        </div>
                        <div class="nom_profil">
                            Joezer
                        </div>
                        <div class="bando"> </div>
                        <div class="menu_group">
                            <div class="ibox animated fadeInRight">
                                <div class="panel panel-success">
                                    <div class="panel-heading">RentHouse infos</div>
                                    <div class="panel-body">
                                        <ul class="nav nav-stacked" style="text-align: left;">
                                            <li><a href="work"><i class="fa fa-home"></i>  Poster une maison</a></li>
                                            <li><a href="#"><i class="fa fa-search-plus"></i>  Rechercher autre </a></li>
                                            <li><a href="pub"><i class="fa fa-street-view"></i>  Business benin</a></li>
                                            <li><a href="#"><i class="fa fa-bar-chart-o"></i>  Business Ghana</a></li>
                                            <li><a href="#"><i class="fa fa-street-view"></i>  Business Togo</a></li>
                                            <li><a href="#"><i class="fa fa-suitcase"></i>  Business Nigeria</a></li>
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="band_publication">
                    <div class="band_pub_head_fixe">
                        <div class="band_pub_head">
                            <div class="bar_search">
                                <form>
                                    <span><input type="text" name=""  class="input" placeholder="searching..."><button type="submit" class="button"><i class="fa fa-search btn-md">Search</i></button></span>
                                </form>
                            </div>
                            <div class="acceuil"><a href="<?php echo $this->url->get('home/index'); ?>" class="lien"><i class="fa fa-home"></i> Acceuil</a></div>
                            <div class="acceuil">
                                <select name="" style="background-color: #afd9ee;">
                                    <option onclick="">Benin</option>
                                    <option>Togo</option>
                                    <option>Nigeria</option>
                                    <option>Ghana</option>
                                    <option>C&ocirc;te d&apos;ivoire</option>
                                    <option>S&eacute;n&eacute;gale</option>

                                </select>

                            </div>
                            <div class="bar_logout"><a href="<?php echo $this->url->get('session/index'); ?>" class="lien">Logout</a></div>
                        </div>
                    </div>

                    <div class="band_pub_contain">
                        <form id="my_form" enctype="multipart/form-data" method="post" action="<?php echo $this->url->get('home/pub'); ?>">
                            <div class="form-group">
                                <section class="col-sm-12">
                                    <div>&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            image:
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="file" multiple="multiple" name="image_pub" class="form-control">
                                        </div>
                                    </div>
                                    <div>&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            Description:
                                        </div>
                                        <div class="col-sm-8">
                                            <textarea name="description_vente" class="form-control" cols="40" rows="8"></textarea>
                                        </div>
                                    </div>
                                    <div>&nbsp;</div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            &nbsp;
                                        </div>
                                        <div class="col-sm-2">
                                            <button type="submit" name="" class="btn btn-primary btn-sm">Save</button>
                                        </div>
                                    </div>

                                </section>
                            </div>


                            <div class="col-md-12">
                                <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
                                    <div><p><?php $this->flashSession->output() ?></p></div>
                                <?php endif; ?>
                            </div>

                        </form>   
                    </div>

                </div>


            </div>
        </div>


    </body>
</html>

